name: Back-end
on:
  workflow_dispatch:
  push:
    paths:
      - 'api/**'
permissions:
  id-token: write
  contents: read
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Zip files
        run: |
          cd api
          zip -r ../visitor_counter.zip main.py
          cd ..
      - name: List file
        run: ls -la
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::508972673429:role/crc-github-actions
          aws-region: ap-southeast-7
      - name: Sync files to S3
        run: aws s3 cp visitor_counter.zip s3://nattapol-crc
      - name: Updata Lambda
        run: aws lambda update-function-code --function-name crc-visitor-counter --s3-bucket nattapol-crc --s3-key visitor_counter.zip --publish