name: Smoke Test
on:
  workflow_call
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install playwright
        run: |
          python3 -m pip install -r requirements.txt
          playwright install 
      - name: Run test
        run: pytest